@JsonPlaceholder.Api_HostAddress = http://localhost:5129

GET {{JsonPlaceholder.Api_HostAddress}}/api/v1/users
Accept: application/json

###

GET {{JsonPlaceholder.Api_HostAddress}}/api/v1/users/1
Accept: application/json

###

GET {{JsonPlaceholder.Api_HostAddress}}/api/v1/posts
Accept: application/json

###